import { PrismaClient, Prisma } from "@prisma/client";
import * as dotenv from "dotenv";
dotenv.config();

const prisma = new PrismaClient({ datasourceUrl: process.env.DATABASE_URL });

const scholarships: Prisma.ScholarshipCreateInput[] = [
    // APPLICATIONS OPEN 
    {
      name: "Mastercard Foundation Scholars — African Institute for Mathematical Sciences (AIMS)",
      provider: "Mastercard Foundation / AIMS",
      country: "South Africa",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Sciences", "Mathématiques"],
      description: "Bourse entièrement financée à l'African Institute for Mathematical Sciences (AIMS) au Cap pour des études post-graduées en mathématiques et sciences.",
      requirements: "Être citoyen d'un pays africain. Licence en mathématiques ou sciences. Excellents résultats académiques.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — African Leadership University (ALU)",
      provider: "Mastercard Foundation / African Leadership University",
      country: "Rwanda",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Leadership", "Entrepreneuriat"],
      description: "Bourse entièrement financée à l'African Leadership University (ALU) à Kigali pour des étudiants africains en licence. Programme axé sur le leadership et l'entrepreneuriat.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés. Fort engagement communautaire.",
      category: "mastercard",
      link: "https://www.alueducation.com/admissions/scholarships/mastercard-foundation-scholars-program/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — American University of Beirut",
      provider: "Mastercard Foundation / American University of Beirut",
      country: "Lebanon",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'American University of Beirut pour des étudiants africains en licence ou master.",
      requirements: "Être citoyen d'un pays africain. Admission à l'AUB. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.aub.edu.lb/oar/Pages/mastercard.aspx",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Arizona State University (ASU)",
      provider: "Mastercard Foundation / Arizona State University",
      country: "USA",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à Arizona State University pour des étudiants africains en master. ASU est reconnue pour son innovation pédagogique et son accessibilité.",
      requirements: "Être citoyen d'un pays africain. Admission à ASU. Excellents résultats académiques. Engagement communautaire.",
      category: "mastercard",
      link: "https://scholarships.asu.edu/mastercard",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Cambridge",
      provider: "Mastercard Foundation / University of Cambridge",
      country: "United Kingdom",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université de Cambridge pour des étudiants africains en master. Couvre les frais de scolarité, le logement, les frais de visa et une allocation mensuelle.",
      requirements: "Être citoyen d'un pays africain. Admission préalable à Cambridge. Excellents résultats académiques. Potentiel de leadership.",
      category: "mastercard",
      link: "https://www.postgraduate.study.cam.ac.uk/funding/mastercard-foundation-scholars-program",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Carnegie Mellon University Africa",
      provider: "Mastercard Foundation / Carnegie Mellon University Africa",
      country: "Rwanda",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Ingénierie", "Informatique"],
      description: "Bourse entièrement financée à CMU-Africa à Kigali pour des masters en ingénierie et informatique. Seul campus de Carnegie Mellon en dehors des États-Unis.",
      requirements: "Être citoyen d'un pays africain. Admission à CMU-Africa. Licence en informatique ou ingénierie. Potentiel de leadership.",
      category: "mastercard",
      link: "https://www.africa.engineering.cmu.edu/admissions/financial-aid.html",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — EARTH University",
      provider: "Mastercard Foundation / EARTH University",
      country: "Costa Rica",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Environnement", "Agriculture"],
      description: "Bourse entièrement financée à EARTH University à San José pour des étudiants africains en licence. Programme axé sur l'agriculture durable et l'environnement.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Intérêt pour l'agriculture et l'environnement. Besoins financiers.",
      category: "mastercard",
      link: "https://earth.ac.cr/en/admissions/scholarships/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Pan-Atlantic University",
      provider: "Mastercard Foundation / Pan-Atlantic University",
      country: "Nigeria",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à la Pan-Atlantic University de Lagos pour des étudiants africains en licence.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés. Engagement communautaire.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Sciences Po Paris",
      provider: "Mastercard Foundation / Sciences Po",
      country: "France",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Sciences Sociales", "Droit", "Sciences Politiques"],
      description: "Bourse entièrement financée à Sciences Po Paris pour des étudiants africains en master. Sciences Po est l'une des meilleures institutions de sciences politiques au monde.",
      requirements: "Être citoyen d'un pays africain. Admission à Sciences Po. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.sciencespo.fr/admissions/en/content/mastercard-foundation-scholars-program.html",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — UC Berkeley",
      provider: "Mastercard Foundation / University of California Berkeley",
      country: "USA",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à UC Berkeley pour des étudiants africains en master dans l'une des meilleures universités publiques du monde.",
      requirements: "Être citoyen d'un pays africain. Admission à UC Berkeley. Excellents résultats. Potentiel de leadership démontré.",
      category: "mastercard",
      link: "https://mastercard.berkeley.edu/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Abomey-Calavi",
      provider: "Mastercard Foundation / University of Abomey-Calavi",
      country: "Benin",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université d'Abomey-Calavi au Bénin pour des étudiants africains en licence.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
  
    // recurrent annually but closed
    {
      name: "Mastercard Foundation Scholars — Ashesi University",
      provider: "Mastercard Foundation / Ashesi University",
      country: "Ghana",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à Ashesi University au Ghana pour des étudiants africains en licence. Ashesi est reconnue pour former des leaders éthiques en Afrique.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés. Fort potentiel de leadership.",
      category: "mastercard",
      link: "https://ashesi.edu.gh/admissions/scholarships/mastercard/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Institut 2iE",
      provider: "Mastercard Foundation / Institut International d'Ingénierie de l'Eau et de l'Environnement",
      country: "Burkina Faso",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Ingénierie", "Environnement"],
      description: "Bourse entièrement financée à l'Institut 2iE à Ouagadougou pour des études en ingénierie de l'eau et de l'environnement au niveau licence et master.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats en sciences et mathématiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — KNUST",
      provider: "Mastercard Foundation / Kwame Nkrumah University of Science & Technology",
      country: "Ghana",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Sciences", "Ingénierie", "Technologies"],
      description: "Bourse entièrement financée à KNUST à Kumasi pour des étudiants africains en licence. KNUST est la première université de sciences et technologies du Ghana.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.knust.edu.gh/admissions/scholarships",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Makerere University",
      provider: "Mastercard Foundation / Makerere University",
      country: "Uganda",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à Makerere University à Kampala pour des étudiants africains en licence. Makerere est l'une des plus anciennes et prestigieuses universités d'Afrique de l'Est.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés. Engagement communautaire.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — McGill University",
      provider: "Mastercard Foundation / McGill University",
      country: "Canada",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à McGill University à Montréal pour des étudiants africains en master dans l'une des universités les plus prestigieuses du Canada.",
      requirements: "Être citoyen d'un pays africain. Admission à McGill. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.mcgill.ca/mastercardfoundation/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — USIU-Africa",
      provider: "Mastercard Foundation / United States International University-Africa",
      country: "Kenya",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à USIU-Africa à Nairobi pour des étudiants africains en licence. USIU-Africa offre une éducation de style américain en Afrique de l'Est.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.usiu.ac.ke/admissions/scholarships/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Université Gaston Berger (UGB)",
      provider: "Mastercard Foundation / Université Gaston Berger",
      country: "Senegal",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université Gaston Berger de Saint-Louis au Sénégal pour des étudiants africains en master.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — Université Mohammed VI Polytechnique",
      provider: "Mastercard Foundation / Université Mohammed VI Polytechnique",
      country: "Morocco",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Sciences", "Ingénierie"],
      description: "Bourse entièrement financée à l'Université Mohammed VI Polytechnique au Maroc pour des étudiants africains en licence et master.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats en sciences et ingénierie. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of British Columbia",
      provider: "Mastercard Foundation / University of British Columbia",
      country: "Canada",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université de Colombie-Britannique à Vancouver pour des étudiants africains en master.",
      requirements: "Être citoyen d'un pays africain. Admission à UBC. Excellents résultats académiques. Potentiel de leadership.",
      category: "mastercard",
      link: "https://you.ubc.ca/financial-planning/scholarships-awards/mastercard-foundation-scholars-program/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Cape Town (UCT)",
      provider: "Mastercard Foundation / University of Cape Town",
      country: "South Africa",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université du Cap pour des étudiants africains en master. UCT est la meilleure université d'Afrique subsaharienne.",
      requirements: "Être citoyen d'un pays africain. Admission à UCT. Excellents résultats académiques. Besoins financiers.",
      category: "mastercard",
      link: "https://www.uct.ac.za/main/explore-uct/funding/mastercard",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Edinburgh",
      provider: "Mastercard Foundation / University of Edinburgh",
      country: "United Kingdom",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université d'Édimbourg pour des étudiants africains en master dans l'une des plus anciennes universités du monde.",
      requirements: "Être citoyen d'un pays africain. Admission à l'Université d'Édimbourg. Excellents résultats académiques.",
      category: "mastercard",
      link: "https://www.ed.ac.uk/student-funding/postgraduate/international/africa/mastercard",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Global Health Equity",
      provider: "Mastercard Foundation / University of Global Health Equity",
      country: "Rwanda",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Médecine", "Santé"],
      description: "Bourse entièrement financée à l'Université of Global Health Equity au Rwanda pour des étudiants africains en master en santé mondiale.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Engagement dans le secteur de la santé.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Gondar",
      provider: "Mastercard Foundation / University of Gondar",
      country: "Ethiopia",
      isFullFunding: true,
      academicLevels: ["BACHELOR"],
      fields: ["Médecine", "Santé", "Sciences"],
      description: "Bourse entièrement financée à l'Université de Gondar en Éthiopie pour des étudiants africains en licence, notamment en médecine et sciences.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Oxford",
      provider: "Mastercard Foundation / University of Oxford",
      country: "United Kingdom",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université d'Oxford pour des étudiants africains en master dans l'une des meilleures universités au monde.",
      requirements: "Être citoyen d'un pays africain. Admission à Oxford. Excellents résultats académiques. Potentiel de leadership exceptionnel.",
      category: "mastercard",
      link: "https://www.ox.ac.uk/admissions/graduate/fees-and-funding/scholarships/mastercard-foundation-scholars-programme",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Pretoria (UP)",
      provider: "Mastercard Foundation / University of Pretoria",
      country: "South Africa",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université de Pretoria pour des étudiants africains en licence et master. UP est l'une des plus grandes universités d'Afrique du Sud.",
      requirements: "Être citoyen d'un pays africain. Admission à UP. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.up.ac.za/mastercard-foundation",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Rwanda",
      provider: "Mastercard Foundation / University of Rwanda",
      country: "Rwanda",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université du Rwanda à Kigali pour des étudiants africains en licence et master.",
      requirements: "Être citoyen d'un pays africain. Excellents résultats académiques. Besoins financiers démontrés. Engagement communautaire.",
      category: "mastercard",
      link: "https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of the Western Cape",
      provider: "Mastercard Foundation / University of the Western Cape",
      country: "South Africa",
      isFullFunding: true,
      academicLevels: ["BACHELOR", "MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université du Western Cape au Cap pour des étudiants africains en licence et master.",
      requirements: "Être citoyen d'un pays africain. Admission à UWC. Excellents résultats académiques. Besoins financiers démontrés.",
      category: "mastercard",
      link: "https://www.uwc.ac.za/study/fees-and-funding/scholarships",
      isTranslated: true,
    },
    {
      name: "Mastercard Foundation Scholars — University of Toronto",
      provider: "Mastercard Foundation / University of Toronto",
      country: "Canada",
      isFullFunding: true,
      academicLevels: ["MASTER"],
      fields: ["Toutes filières"],
      description: "Bourse entièrement financée à l'Université de Toronto pour des étudiants africains en master dans la meilleure université du Canada.",
      requirements: "Être citoyen d'un pays africain. Admission à l'Université de Toronto. Excellents résultats académiques. Potentiel de leadership.",
      category: "mastercard",
      link: "https://future.utoronto.ca/finances/awards/mastercard-foundation-scholars-program/",
      isTranslated: true,
    },
  ];
  
  async function main (){
    console.log("adding total of ${scholarships.length} scholarships...");
    let created = 0;
    let skipped = 0;

    for (const s of scholarships) {
        {const existing = await prisma.scholarship.findFirst({where: {link: s.link}})
        if(existing){
            console.log("skipping already existing scholarship: " + s.name);
            skipped++;
            continue;
        }
            await prisma.scholarship.create({data: s});
            console.log("created scholarship: " +s.name);
            created++;
        }
        console.log("created "+created+" scholarships, skipped "+skipped+" scholarships");
        

    }
  }
  main().catch(console.error).finally(() => prisma.$disconnect());
